const app=document.getElementById("app");let DATA=null;let state={cls:null,sub:null,ch:null,topic:null};
async function load(){try{const r=await fetch("data.json?"+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);DATA=await r.json();renderClasses()}catch(e){app.innerHTML=`<div class="error"><b>data.json लोड नहीं हुआ</b><br>कृपया GitHub में data.json को इसी folder में रखें।<br><span class="small">${e.message}</span></div>`}}
function btn(name,fn){const b=document.createElement('button');b.className='btn';b.textContent=name;b.onclick=fn;return b}
function shell(title,back){app.innerHTML='';let c=document.createElement('div');c.className='card';if(back)c.appendChild(btn('← वापस',back));let h=document.createElement('h2');h.textContent=title;c.appendChild(h);app.appendChild(c);return c}
function renderClasses(){let c=shell('कक्षा चुनें');let g=document.createElement('div');g.className='grid';Object.keys(DATA.classes).forEach(k=>g.appendChild(btn('कक्षा '+k,()=>renderSubjects(k))));c.appendChild(g)}
function renderSubjects(k){state.cls=k;let c=shell('कक्षा '+k,renderClasses),g=document.createElement('div');g.className='grid';Object.values(DATA.classes[k].subjects).forEach(s=>g.appendChild(btn(s.name,()=>renderChapters(s))));c.appendChild(g)}
function renderChapters(s){state.sub=s;let c=shell(s.name,()=>renderSubjects(state.cls)),g=document.createElement('div');g.className='grid';s.chapters.forEach(ch=>g.appendChild(btn(ch.name,()=>renderTopics(ch))));c.appendChild(g)}
function renderTopics(ch){state.ch=ch;let c=shell(ch.name,()=>renderChapters(state.sub)),g=document.createElement('div');g.className='grid';ch.topics.forEach(t=>g.appendChild(btn(t.name,()=>quiz(t))));c.appendChild(g)}
function quiz(t){state.topic=t;let qs=t.questions||[];let c=shell(t.name,()=>renderTopics(state.ch));if(!qs.length){c.insertAdjacentHTML('beforeend','<div class="error">इस topic में प्रश्न नहीं हैं।</div>');return}qs.forEach((q,i)=>{let box=document.createElement('div');box.className='card';box.innerHTML=`<div class="small">प्रश्न ${i+1} / ${qs.length}</div><div class="q">${esc(q.q)}</div>`;q.options.forEach((o,j)=>{let b=document.createElement('button');b.className='opt';b.textContent=String.fromCharCode(65+j)+'. '+o;b.onclick=()=>{box.querySelectorAll('.opt').forEach((x,n)=>{x.disabled=true;if(n===q.answer)x.classList.add('ok');else if(n===j)x.classList.add('bad')});let s=box.querySelector('.solution');s.style.display='block'};box.appendChild(b)});let sol=document.createElement('div');sol.className='solution';sol.innerHTML='<b>उत्तर/Concept:</b> '+esc(q.solution);box.appendChild(sol);c.appendChild(box)})}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
load();